install:
        # The version of pandoc that ships with Ubuntu at the time of writing doesn't have the --metadata-file switch
        - wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-1-amd64.deb
        - sudo dpkg -i pandoc-2.7.1-1-amd64.deb
        - sudo apt-get install -y texlive-latex-base
        - sudo apt-get install -y texlive-latex-recommended
        - sudo apt-get install -y texlive-fonts-recommended

script:
        "pandoc --metadata-file=./pandoc_latex.yml  Readme.md  -o Readme.pdf"
