install:
        # The version of pandoc that ships with Ubuntu at the time of writing doesn't have the --metadata-file switch
        - wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-1-amd64.deb
        - sudo dpkg -i pandoc-2.7.1-1-amd64.deb
        - sudo apt-get install -y texlive-latex-base
        - sudo apt-get install -y texlive-latex-recommended
        - sudo apt-get install -y texlive-fonts-recommended

script:
        "pandoc -f markdown+fancy_lists --metadata-file=./pandoc_latex.yml  NAG_kdb.md  -o NAG_kdb.pdf"

deploy:
        provider: pages
        skip-cleanup: true
        github-token: $ghtok  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
